cmake_minimum_required(VERSION 3.16)
find_package(Git REQUIRED QUIET)
if(NOT DEFINED ONEUI_ICU_ROOT OR NOT DEFINED ONEUI_TEST_ROOT)
    message(FATAL_ERROR "ICU source and test output roots are required")
endif()
set(_source "${ONEUI_ICU_ROOT}")
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef _suffix)
set(_fixture "${ONEUI_TEST_ROOT}/icu-patch-fixture-${_suffix}")
# Never reset the real dependency checkout. This shared, no-checkout clone
# writes only its own metadata and the two small patch-input fixtures.
execute_process(COMMAND "${GIT_EXECUTABLE}" clone --shared --no-checkout --quiet "${_source}" "${_fixture}" RESULT_VARIABLE _result)
if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Could not create isolated ICU patch fixture")
endif()
execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${_fixture}" checkout HEAD -- source/common/ubidi.cpp source/common/ubidiimp.h RESULT_VARIABLE _result)
if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Could not populate ICU patch fixture")
endif()
set(_script "${CMAKE_CURRENT_LIST_DIR}/../scripts/apply-skia-patches.cmake")
function(run_recipe check_only expected_success expected_message)
    file(SHA256 "${_fixture}/source/common/ubidi.cpp" _before)
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DONEUI_ICU_ROOT=${_fixture}" "-DONEUI_ICU_CHECK_ONLY=${check_only}" -P "${_script}"
        RESULT_VARIABLE _result OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr)
    if(expected_success AND NOT _result EQUAL 0)
        message(FATAL_ERROR "Expected patch success: ${_stdout}\n${_stderr}")
    elseif(NOT expected_success AND _result EQUAL 0)
        message(FATAL_ERROR "Expected patch rejection")
    endif()
    if(NOT "${_stdout}${_stderr}" MATCHES "${expected_message}")
        message(FATAL_ERROR "Unexpected patch diagnostic: ${_stdout}\n${_stderr}")
    endif()
    if(check_only OR NOT expected_success)
        file(SHA256 "${_fixture}/source/common/ubidi.cpp" _after)
        if(NOT _before STREQUAL _after)
            message(FATAL_ERROR "Read-only/rejected patch modified the fixture")
        endif()
    endif()
endfunction()
run_recipe(ON FALSE "patch is absent")
run_recipe(OFF TRUE "Applied OneUI")
file(SHA256 "${_fixture}/source/common/ubidi.cpp" _applied)
run_recipe(OFF TRUE "already applied")
file(SHA256 "${_fixture}/source/common/ubidi.cpp" _reapplied)
if(NOT _applied STREQUAL _reapplied)
    message(FATAL_ERROR "Repeated application was not idempotent")
endif()
run_recipe(ON TRUE "already applied")
# Generated adversarial fixture: an unrelated local edit must survive failure.
file(APPEND "${_fixture}/source/common/ubidi.cpp" "\n// Local fixture edit: preserve me.\n")
run_recipe(OFF FALSE "unrecognized local changes")
run_recipe(ON FALSE "unrecognized local changes")
message(STATUS "ICU patch pristine/apply/reapply/read-only/conflict checks passed; fixture: ${_fixture}")
