cmake_minimum_required(VERSION 3.16)
find_package(Git REQUIRED QUIET)
if(NOT DEFINED ONEUI_SKIA_ROOT OR NOT DEFINED ONEUI_TEST_ROOT)
    message(FATAL_ERROR "Skia source and test output roots are required")
endif()
string(RANDOM LENGTH 12 ALPHABET 0123456789abcdef _suffix)
set(_fixture "${ONEUI_TEST_ROOT}/win7-patch-fixture-${_suffix}")
# All mutations are confined to a new fixture; never reset a dependency checkout.
execute_process(COMMAND "${GIT_EXECUTABLE}" clone --shared --no-checkout --quiet "${ONEUI_SKIA_ROOT}" "${_fixture}" RESULT_VARIABLE _result)
if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Could not create isolated Skia patch fixture")
endif()
set(_files src/ports/SkFontMgr_win_dw.cpp src/utils/win/SkDWrite.cpp)
execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${_fixture}" checkout HEAD -- ${_files} RESULT_VARIABLE _result)
if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Could not populate Skia patch fixture")
endif()
set(_script "${CMAKE_CURRENT_LIST_DIR}/../scripts/apply-skia-win7-patches.cmake")
function(run_recipe check_only expected_success diagnostic)
    foreach(_file IN LISTS _files)
        file(SHA256 "${_fixture}/${_file}" "before_${_file}")
    endforeach()
    execute_process(COMMAND "${CMAKE_COMMAND}" "-DONEUI_SKIA_ROOT=${_fixture}" "-DONEUI_SKIA_CHECK_ONLY=${check_only}" -P "${_script}"
        RESULT_VARIABLE _result OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr)
    if(expected_success AND NOT _result EQUAL 0)
        message(FATAL_ERROR "Expected patch success: ${_stdout}\n${_stderr}")
    elseif(NOT expected_success AND _result EQUAL 0)
        message(FATAL_ERROR "Expected patch rejection")
    endif()
    if(NOT "${_stdout}${_stderr}" MATCHES "${diagnostic}")
        message(FATAL_ERROR "Unexpected diagnostic: ${_stdout}\n${_stderr}")
    endif()
    if(check_only OR NOT expected_success)
        foreach(_file IN LISTS _files)
            file(SHA256 "${_fixture}/${_file}" _after)
            if(NOT "${before_${_file}}" STREQUAL "${_after}")
                message(FATAL_ERROR "Read-only/rejected patch modified ${_file}")
            endif()
        endforeach()
    endif()
endfunction()
run_recipe(ON FALSE "patch is absent")
run_recipe(OFF TRUE "Applied Win7")
run_recipe(OFF TRUE "already applied")
run_recipe(ON TRUE "already applied")
# Revert only the newly generated fixture's loader to simulate a partial patch.
execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${_fixture}" checkout HEAD -- src/utils/win/SkDWrite.cpp RESULT_VARIABLE _result)
if(NOT _result EQUAL 0)
    message(FATAL_ERROR "Could not prepare partial-patch fixture")
endif()
run_recipe(OFF FALSE "unrecognized local changes")
run_recipe(ON FALSE "unrecognized local changes")
file(APPEND "${_fixture}/src/ports/SkFontMgr_win_dw.cpp" "\n// Local test edit: preserve me.\n")
run_recipe(OFF FALSE "unrecognized local changes")
message(STATUS "Win7 patch pristine/apply/reapply/read-only/partial/conflict checks passed; fixture: ${_fixture}")
