cmake_minimum_required(VERSION 3.16)
# Also included by OneUIText.cmake in read-only mode. Hashes use LF-normalized
# UTF-8 so Windows Git line-ending conversion does not change patch identity.
if(NOT DEFINED ONEUI_ICU_ROOT)
    get_filename_component(ONEUI_ICU_ROOT "${CMAKE_CURRENT_LIST_DIR}/../third_party/skia/third_party/externals/icu" ABSOLUTE)
endif()
set(_oneui_icu_pin "364118a1d9da24bb5b770ac3d762ac144d6da5a4")
set(_oneui_icu_patch "${CMAKE_CURRENT_LIST_DIR}/../third_party/patches/icu-74.2-bidi-unicode-15.1.patch")
find_package(Git REQUIRED QUIET)
if(NOT EXISTS "${ONEUI_ICU_ROOT}/.git")
    message(FATAL_ERROR "Expected the pinned ICU checkout at ${ONEUI_ICU_ROOT}; sync Skia DEPS first.")
endif()
execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${ONEUI_ICU_ROOT}" rev-parse HEAD
    RESULT_VARIABLE _oneui_icu_git_result OUTPUT_VARIABLE _oneui_icu_revision OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT _oneui_icu_git_result EQUAL 0 OR NOT _oneui_icu_revision STREQUAL _oneui_icu_pin)
    message(FATAL_ERROR "ICU must remain at reviewed base ${_oneui_icu_pin}; found ${_oneui_icu_revision}. No files changed.")
endif()

function(oneui_icu_source_hash path output)
    file(READ "${ONEUI_ICU_ROOT}/${path}" _source)
    string(REPLACE "\r\n" "\n" _source "${_source}")
    string(SHA256 _hash "${_source}")
    set(${output} "${_hash}" PARENT_SCOPE)
endfunction()
function(oneui_icu_patch_state output)
    oneui_icu_source_hash(source/common/ubidi.cpp _cpp)
    oneui_icu_source_hash(source/common/ubidiimp.h _header)
    if(_cpp STREQUAL "567ebda2ffcc7877ee42e92352f253cc4e6d04f72e4520a593918a419d7770bf" AND
       _header STREQUAL "b6ffb0eeb27bf0c8025938b92bb22a7fa00cde836254c81da4eae8c5ee637513")
        set(${output} applied PARENT_SCOPE)
    elseif(_cpp STREQUAL "57f4057b709cf38ed497f940cb09a92e0e24ce29ac3cde30f652e533bcb9a5a0" AND
           _header STREQUAL "2b432c4648d3132b7a129a007f880c8964d194ad0bb2b4494e656cb2a8c38586")
        set(${output} pristine PARENT_SCOPE)
    else()
        message(FATAL_ERROR "ICU patch inputs have unrecognized local changes. Preserving ${ONEUI_ICU_ROOT}; review the conflict manually.")
    endif()
endfunction()

oneui_icu_patch_state(_oneui_icu_state)
if(_oneui_icu_state STREQUAL pristine)
    if(ONEUI_ICU_CHECK_ONLY)
        message(FATAL_ERROR "Required Unicode 15.1 ICU patch is absent. Run the Skia build script to apply it and rebuild ALL text archives before configuring OneUI.")
    endif()
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${ONEUI_ICU_ROOT}" apply --check --whitespace=error "${_oneui_icu_patch}"
        RESULT_VARIABLE _oneui_icu_check)
    if(NOT _oneui_icu_check EQUAL 0)
        message(FATAL_ERROR "ICU patch preflight failed. No files changed.")
    endif()
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${ONEUI_ICU_ROOT}" apply --whitespace=error "${_oneui_icu_patch}"
        RESULT_VARIABLE _oneui_icu_apply)
    if(NOT _oneui_icu_apply EQUAL 0)
        message(FATAL_ERROR "ICU patch application failed; inspect the checkout before continuing.")
    endif()
    oneui_icu_patch_state(_oneui_icu_state)
    if(NOT _oneui_icu_state STREQUAL applied)
        message(FATAL_ERROR "ICU post-application verification failed.")
    endif()
    message(STATUS "Applied OneUI's ICU 74.2 / Unicode 15.1 Bidi patch; rebuild skia, skparagraph and skunicode_icu.")
else()
    message(STATUS "Verified OneUI's ICU 74.2 / Unicode 15.1 Bidi patch (already applied)")
endif()
