cmake_minimum_required(VERSION 3.16)
if(NOT DEFINED ONEUI_SKIA_ROOT)
    get_filename_component(ONEUI_SKIA_ROOT "${CMAKE_CURRENT_LIST_DIR}/../third_party/skia" ABSOLUTE)
endif()
find_package(Git REQUIRED QUIET)
execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${ONEUI_SKIA_ROOT}" rev-parse HEAD
    RESULT_VARIABLE _result OUTPUT_VARIABLE _revision OUTPUT_STRIP_TRAILING_WHITESPACE)
if(NOT _result EQUAL 0 OR NOT _revision STREQUAL "1f26101197bff9fcd939a791beb3094297436d59")
    message(FATAL_ERROR "Win7 Skia patch requires the reviewed Skia revision; no files changed")
endif()
set(_input "${ONEUI_SKIA_ROOT}/src/ports/SkFontMgr_win_dw.cpp")
set(_patch "${CMAKE_CURRENT_LIST_DIR}/../third_party/patches/skia-win7-directwrite-fallback.patch")
file(READ "${_input}" _source)
string(REPLACE "\r\n" "\n" _source "${_source}")
string(SHA256 _hash "${_source}")
file(READ "${ONEUI_SKIA_ROOT}/src/utils/win/SkDWrite.cpp" _loader)
string(REPLACE "\r\n" "\n" _loader "${_loader}")
string(SHA256 _loader_hash "${_loader}")
if(_hash STREQUAL "51776ec6a0d32c4a56653eb5bb920c8c29cfd55d6a25932f0bc32635f88d2671" AND
   _loader_hash STREQUAL "be8d38298d85ccaea87fd9c75c46532614b23b35751fc2d58b443ef1efbd9444")
    message(STATUS "Verified Win7 DirectWrite fallback patch (already applied)")
elseif(_hash STREQUAL "db988455c919caabaf1319f49a4dd46aa051ad3b9bae7dbaefafafb4aefe0557" AND
       _loader_hash STREQUAL "fa286bdffb5393ff387c2a98c1289f88dd273fa2d9bc48d2d83b0c7390a04ccf")
    if(ONEUI_SKIA_CHECK_ONLY)
        message(FATAL_ERROR "Win7 DirectWrite patch is absent; rebuild the Win7 Skia archives first")
    endif()
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${ONEUI_SKIA_ROOT}" apply --check --whitespace=error "${_patch}" RESULT_VARIABLE _result)
    if(NOT _result EQUAL 0)
        message(FATAL_ERROR "Win7 patch preflight failed; no files changed")
    endif()
    execute_process(COMMAND "${GIT_EXECUTABLE}" -C "${ONEUI_SKIA_ROOT}" apply --whitespace=error "${_patch}" RESULT_VARIABLE _result)
    if(NOT _result EQUAL 0)
        message(FATAL_ERROR "Win7 patch application failed")
    endif()
    file(READ "${_input}" _source)
    string(REPLACE "\r\n" "\n" _source "${_source}")
    string(SHA256 _hash "${_source}")
    file(READ "${ONEUI_SKIA_ROOT}/src/utils/win/SkDWrite.cpp" _loader)
    string(REPLACE "\r\n" "\n" _loader "${_loader}")
    string(SHA256 _loader_hash "${_loader}")
    if(NOT _hash STREQUAL "51776ec6a0d32c4a56653eb5bb920c8c29cfd55d6a25932f0bc32635f88d2671" OR
       NOT _loader_hash STREQUAL "be8d38298d85ccaea87fd9c75c46532614b23b35751fc2d58b443ef1efbd9444")
        message(FATAL_ERROR "Win7 patch post-application verification failed")
    endif()
    message(STATUS "Applied Win7 DirectWrite fallback patch; rebuild Skia")
else()
    message(FATAL_ERROR "Win7 patch input has unrecognized local changes; preserving the checkout")
endif()
