get_filename_component(root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
file(READ "${root}/include/oneui/oneui_c_api.h" header)
file(GLOB_RECURSE bindings "${root}/bindings/rust/oneui-sys/src/*.rs")
set(rust "")
foreach(binding IN LISTS bindings)
    file(READ "${binding}" source)
    string(APPEND rust "\n${source}")
endforeach()
string(REGEX MATCH "#define[ \t]+ONEUI_UTF8_ABI_VERSION[ \t]+([0-9]+)u" unused "${header}")
set(c_version "${CMAKE_MATCH_1}")
string(REGEX MATCH "pub const UTF8_ABI_VERSION:[ \t]*c_uint[ \t]*=[ \t]*([0-9]+);" unused "${rust}")
if(c_version STREQUAL "" OR NOT c_version STREQUAL CMAKE_MATCH_1)
    message(FATAL_ERROR "C/Rust ABI version mismatch: ${c_version} / ${CMAKE_MATCH_1}")
endif()
file(STRINGS "${root}/bindings/rust/oneui-sys/supported-symbols.txt" expected REGEX "^oneui_")
string(REGEX MATCHALL "pub fn[ \t]+oneui_[a-z0-9_]+[ \t]*\\(" declarations "${rust}")
set(actual "")
foreach(declaration IN LISTS declarations)
    string(REGEX MATCH "oneui_[a-z0-9_]+" symbol "${declaration}")
    list(APPEND actual "${symbol}")
    if(NOT header MATCHES "${symbol}[ \t\r\n]*\\(")
        message(FATAL_ERROR "Rust symbol missing from C header: ${symbol}")
    endif()
endforeach()
list(REMOVE_DUPLICATES actual)
list(SORT actual)
list(SORT expected)
if(NOT "${actual}" STREQUAL "${expected}")
    message(FATAL_ERROR "Rust FFI and supported-symbols.txt differ; review additions/removals explicitly")
endif()
message(STATUS "OneUI C/Rust ABI and explicit FFI symbol manifest agree")
