get_filename_component(root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
if(NOT ONEUI_TEXT_TEST_ASSET_ROOT)
    set(ONEUI_TEXT_TEST_ASSET_ROOT "${root}/out/text-assets")
endif()
file(MAKE_DIRECTORY "${ONEUI_TEXT_TEST_ASSET_ROOT}")
function(oneui_text_asset name hash url license)
    set(path "${ONEUI_TEXT_TEST_ASSET_ROOT}/${name}")
    if(EXISTS "${path}")
        file(SHA256 "${path}" actual)
        if(actual STREQUAL hash)
            return()
        endif()
        message(FATAL_ERROR "Existing text test asset has an unexpected checksum: ${path}")
    endif()
    message(STATUS "Fetching ${name} (${license})")
    file(DOWNLOAD "${url}" "${path}" EXPECTED_HASH "SHA256=${hash}" TLS_VERIFY ON STATUS status)
    list(GET status 0 code)
    if(NOT code EQUAL 0)
        message(FATAL_ERROR "Text test asset download failed: ${status}")
    endif()
endfunction()
include("${root}/tests/text-assets.cmake")
