function(oneui_add_core_test target source)
    add_executable(${target} ${source})
    target_link_libraries(${target} PRIVATE oneui_core)
    target_compile_definitions(${target} PRIVATE ONEUI_BUILDING_DLL)
    add_test(NAME ${target} COMMAND ${target})
endfunction()

function(oneui_add_native_test target source)
    add_executable(${target} ${source})
    target_link_libraries(${target} PRIVATE oneui)
    add_test(NAME ${target} COMMAND ${target})
endfunction()

function(oneui_register_core_tests)
    if(ONEUI_SKIA_MODE STREQUAL "bundled-static")
        add_test(NAME oneui_icu_patch_recipe_tests COMMAND "${CMAKE_COMMAND}"
            "-DONEUI_ICU_ROOT=${ONEUI_BUNDLED_SKIA_ROOT}/third_party/externals/icu"
            "-DONEUI_TEST_ROOT=${CMAKE_CURRENT_BINARY_DIR}"
            -P "${PROJECT_SOURCE_DIR}/tests/icu_patch_recipe_tests.cmake")
    endif()
    set(ONEUI_TEXT_TEST_ASSET_ROOT "${PROJECT_SOURCE_DIR}/out/text-assets" CACHE PATH "Pinned Unicode/font acceptance assets")
    function(oneui_text_asset name hash url license)
        set(path "${ONEUI_TEXT_TEST_ASSET_ROOT}/${name}")
        if(NOT EXISTS "${path}")
            message(FATAL_ERROR "Required text test asset missing: ${path}. Run cmake -P scripts/fetch-text-test-assets.cmake")
        endif()
        file(SHA256 "${path}" actual)
        if(NOT actual STREQUAL hash)
            message(FATAL_ERROR "Text test asset checksum mismatch: ${path}")
        endif()
    endfunction()
    include("${PROJECT_SOURCE_DIR}/tests/text-assets.cmake")
    add_executable(oneui_unicode_conformance_tests tests/unicode_conformance_tests.cpp)
    target_include_directories(oneui_unicode_conformance_tests PRIVATE src include "${ONEUI_BUNDLED_SKIA_ROOT}/third_party/externals/icu/source/common")
    target_link_libraries(oneui_unicode_conformance_tests PRIVATE oneui_text)
    target_compile_definitions(oneui_unicode_conformance_tests PRIVATE ONEUI_TEXT_ASSETS="${ONEUI_TEXT_TEST_ASSET_ROOT}")
    if(ONEUI_SKIA_MODE STREQUAL "bundled-static")
        target_compile_definitions(oneui_unicode_conformance_tests PRIVATE U_STATIC_IMPLEMENTATION U_DISABLE_RENAMING=1)
    endif()
    add_test(NAME oneui_unicode_conformance_tests COMMAND oneui_unicode_conformance_tests)
    oneui_add_core_test(oneui_interaction_tests tests/interaction_tests.cpp)
    target_include_directories(oneui_interaction_tests PRIVATE src)
    add_executable(oneui_reactive_lifetime_tests tests/reactive_lifetime_tests.cpp)
    target_include_directories(oneui_reactive_lifetime_tests PRIVATE include)
    add_test(NAME oneui_reactive_lifetime_tests COMMAND oneui_reactive_lifetime_tests)
    add_executable(oneui_text_layout_tests tests/text_layout_tests.cpp)
    target_include_directories(oneui_text_layout_tests PRIVATE src include)
    target_compile_definitions(oneui_text_layout_tests PRIVATE ONEUI_TEXT_ASSETS="${ONEUI_TEXT_TEST_ASSET_ROOT}")
    target_link_libraries(oneui_text_layout_tests PRIVATE oneui_text)
    add_test(NAME oneui_text_layout_tests COMMAND oneui_text_layout_tests)
    oneui_add_core_test(oneui_portable_text_tests tests/portable_text_tests.cpp)
    target_include_directories(oneui_portable_text_tests PRIVATE src)
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        find_package(Threads REQUIRED)
        add_executable(oneui_linux_pipe_tests tests/linux_pipe_tests.cpp)
        target_include_directories(oneui_linux_pipe_tests PRIVATE src)
        target_link_libraries(oneui_linux_pipe_tests PRIVATE Threads::Threads)
        add_test(NAME oneui_linux_pipe_tests COMMAND oneui_linux_pipe_tests)
    endif()
    oneui_add_core_test(oneui_control_behavior_tests tests/control_behavior_tests.cpp)
    target_include_directories(oneui_control_behavior_tests PRIVATE src)
    oneui_add_core_test(oneui_time_series_chart_behavior_tests tests/time_series_chart_behavior_tests.cpp)
    oneui_add_core_test(oneui_selection_model_tests tests/selection_model_tests.cpp)
    oneui_add_core_test(oneui_overlay_host_behavior_tests tests/overlay_host_behavior_tests.cpp)
    oneui_add_core_test(oneui_scroll_view_behavior_tests tests/scroll_view_behavior_tests.cpp)
    oneui_add_core_test(oneui_stack_behavior_tests tests/stack_behavior_tests.cpp)
    oneui_add_core_test(oneui_realtime_frame_view_behavior_tests tests/realtime_frame_view_behavior_tests.cpp)
    oneui_add_core_test(oneui_remote_input_region_behavior_tests tests/remote_input_region_behavior_tests.cpp)
    oneui_add_core_test(oneui_terminal_view_behavior_tests tests/terminal_view_behavior_tests.cpp)
    oneui_add_core_test(oneui_tree_view_behavior_tests tests/tree_view_behavior_tests.cpp)
    oneui_add_core_test(oneui_panel_behavior_tests tests/panel_behavior_tests.cpp)
endfunction()

function(oneui_register_native_tests)
    oneui_add_native_test(oneui_interaction_c_api_tests tests/interaction_c_api_tests.cpp)
    if(UNIX)
        oneui_add_native_test(oneui_desktop_input_tests tests/desktop_input_tests.cpp)
        target_include_directories(oneui_desktop_input_tests PRIVATE src)
    endif()
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        add_executable(oneui_backend_selection_tests tests/backend_selection_tests.cpp)
        target_link_libraries(oneui_backend_selection_tests PRIVATE oneui)
        add_test(NAME oneui_backend_explicit_failure COMMAND oneui_backend_selection_tests failure)
        set_tests_properties(oneui_backend_explicit_failure PROPERTIES
            ENVIRONMENT "ONEUI_LINUX_BACKEND=wayland;WAYLAND_DISPLAY=oneui-nonexistent-test-socket")
        add_test(NAME oneui_backend_invalid_selection COMMAND oneui_backend_selection_tests failure)
        set_tests_properties(oneui_backend_invalid_selection PROPERTIES ENVIRONMENT "ONEUI_LINUX_BACKEND=invalid")
        if(NOT "$ENV{DISPLAY}" STREQUAL "")
            add_executable(oneui_x11_clipboard_peer_tests tests/x11_clipboard_peer_tests.cpp)
            target_include_directories(oneui_x11_clipboard_peer_tests PRIVATE src)
            target_link_libraries(oneui_x11_clipboard_peer_tests PRIVATE PkgConfig::ONEUI_LINUX)
            add_test(NAME oneui_x11_clipboard_peer_tests COMMAND oneui_x11_clipboard_peer_tests)
            add_test(NAME oneui_backend_auto_fallback COMMAND oneui_backend_selection_tests x11)
            set_tests_properties(oneui_backend_auto_fallback PROPERTIES
                ENVIRONMENT "ONEUI_LINUX_BACKEND=auto;WAYLAND_DISPLAY=oneui-nonexistent-test-socket")
        endif()
    endif()
    oneui_add_native_test(oneui_c_api_behavior_tests tests/c_api_behavior_tests.cpp)
    oneui_add_native_test(oneui_c_api_workspace_tests tests/c_api_workspace_tests.cpp)
    oneui_add_native_test(oneui_time_series_chart_c_api_tests tests/time_series_chart_c_api_tests.cpp)
    oneui_add_native_test(oneui_monitor_behavior_tests tests/monitor_behavior_tests.cpp)
    target_compile_definitions(oneui_monitor_behavior_tests PRIVATE ONEUI_BUILDING_DLL)
    oneui_add_native_test(oneui_backend_contract_tests tests/backend_contract_tests.cpp)
    target_compile_definitions(oneui_backend_contract_tests PRIVATE ONEUI_BUILDING_DLL)
    add_test(NAME oneui_system_clipboard_tests COMMAND oneui_backend_contract_tests --clipboard)
    set_tests_properties(oneui_system_clipboard_tests PROPERTIES SKIP_RETURN_CODE 77 LABELS "native-acceptance")

    if(ONEUI_BUILD_STATIC)
        add_executable(oneui_interaction_static_tests tests/interaction_c_api_tests.cpp)
        target_link_libraries(oneui_interaction_static_tests PRIVATE oneui_static)
        target_compile_definitions(oneui_interaction_static_tests PRIVATE ONEUI_STATIC)
        add_test(NAME oneui_interaction_static_tests COMMAND oneui_interaction_static_tests)
        add_executable(oneui_c_api_static_link_tests tests/c_api_behavior_tests.cpp)
        target_link_libraries(oneui_c_api_static_link_tests PRIVATE oneui_static)
        target_compile_definitions(oneui_c_api_static_link_tests PRIVATE ONEUI_STATIC)
        add_test(NAME oneui_c_api_static_link_tests COMMAND oneui_c_api_static_link_tests)
    endif()

    add_test(
        NAME oneui_abi_sync
        COMMAND ${CMAKE_COMMAND} -P ${CMAKE_CURRENT_SOURCE_DIR}/scripts/check-abi-sync.cmake)
endfunction()
