set(_oneui_desktop_sources
    src/platform/shared/desktop_window.cpp
    src/platform/shared/skia_canvas.cpp
    src/platform/shared/skia_path.cpp)
find_package(Threads REQUIRED)
set(_oneui_desktop_libraries oneui_text oneui_skia Threads::Threads)
if(APPLE)
    enable_language(OBJCXX)
    set(CMAKE_OBJCXX_STANDARD 17)
    set(CMAKE_OBJCXX_STANDARD_REQUIRED ON)
    if(NOT CMAKE_OSX_DEPLOYMENT_TARGET)
        set(CMAKE_OSX_DEPLOYMENT_TARGET "13.0")
    endif()
    list(APPEND _oneui_desktop_sources src/platform/macos/window_macos.mm)
    list(APPEND _oneui_desktop_libraries "-framework Cocoa" "-framework CoreText" "-framework CoreGraphics")
    set_source_files_properties(src/platform/macos/window_macos.mm PROPERTIES COMPILE_OPTIONS "-fobjc-arc")
else()
    enable_language(C)
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(ONEUI_LINUX REQUIRED IMPORTED_TARGET x11 xrandr wayland-client wayland-cursor xkbcommon fontconfig)
    find_program(WAYLAND_SCANNER wayland-scanner)
    if(NOT WAYLAND_SCANNER)
        message(FATAL_ERROR "wayland-scanner is required for the native Wayland backend")
    endif()
    pkg_get_variable(WAYLAND_PROTOCOLS_DIR wayland-protocols pkgdatadir)
    file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/protocols")
    set(_oneui_protocols xdg-shell text-input-unstable-v3 viewporter)
    if(EXISTS "${WAYLAND_PROTOCOLS_DIR}/staging/fractional-scale/fractional-scale-v1.xml")
        list(APPEND _oneui_protocols fractional-scale-v1)
        set(_oneui_fractional_scale ON)
    else()
        message(STATUS "fractional-scale-v1 unavailable: Wayland will use integer output scaling")
    endif()
    foreach(_protocol IN LISTS _oneui_protocols)
        if(_protocol STREQUAL "xdg-shell" OR _protocol STREQUAL "viewporter")
            set(_xml "${WAYLAND_PROTOCOLS_DIR}/stable/${_protocol}/${_protocol}.xml")
        elseif(_protocol STREQUAL "fractional-scale-v1")
            set(_xml "${WAYLAND_PROTOCOLS_DIR}/staging/fractional-scale/${_protocol}.xml")
        else()
            set(_xml "${WAYLAND_PROTOCOLS_DIR}/unstable/text-input/${_protocol}.xml")
        endif()
        set(_header "${CMAKE_CURRENT_BINARY_DIR}/protocols/${_protocol}-client-protocol.h")
        set(_code "${CMAKE_CURRENT_BINARY_DIR}/protocols/${_protocol}-protocol.c")
        add_custom_command(OUTPUT "${_header}" "${_code}"
            COMMAND "${WAYLAND_SCANNER}" client-header "${_xml}" "${_header}"
            COMMAND "${WAYLAND_SCANNER}" private-code "${_xml}" "${_code}"
            DEPENDS "${_xml}" VERBATIM)
        list(APPEND _oneui_desktop_sources "${_header}" "${_code}")
    endforeach()
    list(APPEND _oneui_desktop_sources src/platform/linux/window_linux.cpp
        src/platform/linux/window_x11.cpp src/platform/linux/window_wayland.cpp)
    list(APPEND _oneui_desktop_libraries PkgConfig::ONEUI_LINUX ${CMAKE_DL_LIBS})
endif()

add_library(oneui_platform_desktop OBJECT ${_oneui_desktop_sources})
set_target_properties(oneui_platform_desktop PROPERTIES POSITION_INDEPENDENT_CODE ON)
target_include_directories(oneui_platform_desktop PRIVATE include src "${CMAKE_CURRENT_BINARY_DIR}/protocols")
target_link_libraries(oneui_platform_desktop PUBLIC ${_oneui_desktop_libraries})
target_compile_definitions(oneui_platform_desktop PRIVATE ONEUI_BUILDING_DLL)
if(_oneui_fractional_scale)
    target_compile_definitions(oneui_platform_desktop PRIVATE ONEUI_HAVE_FRACTIONAL_SCALE=1)
endif()
if(ONEUI_ENABLE_TEST_FRAME_CAPTURE)
    target_compile_definitions(oneui_platform_desktop PRIVATE ONEUI_ENABLE_TEST_FRAME_CAPTURE=1)
endif()
add_library(oneui SHARED ${ONEUI_C_API_SOURCES}
    $<TARGET_OBJECTS:oneui_core> $<TARGET_OBJECTS:oneui_platform_desktop>)
target_link_libraries(oneui PRIVATE ${_oneui_desktop_libraries})
target_include_directories(oneui PUBLIC include)
target_compile_definitions(oneui PRIVATE ONEUI_BUILDING_DLL)
if(APPLE)
    set_target_properties(oneui PROPERTIES INSTALL_NAME_DIR "@rpath" INSTALL_RPATH "@loader_path")
else()
    set_target_properties(oneui PROPERTIES INSTALL_RPATH "$ORIGIN")
    # Embedded ICU/HarfBuzz/Skia are private to this DSO, including references
    # from other archives; a host's ICU must not interpose a different version.
    target_link_options(oneui PRIVATE "-Wl,--exclude-libs,ALL")
endif()
add_library(OneUI::oneui ALIAS oneui)
if(ONEUI_BUILD_STATIC)
    add_library(oneui_static STATIC ${ONEUI_C_API_SOURCES}
        $<TARGET_OBJECTS:oneui_core> $<TARGET_OBJECTS:oneui_platform_desktop>)
    target_link_libraries(oneui_static PUBLIC ${_oneui_desktop_libraries})
    target_include_directories(oneui_static PUBLIC include)
    target_compile_definitions(oneui_static PUBLIC ONEUI_STATIC)
    add_library(OneUI::oneui_static ALIAS oneui_static)
endif()
add_subdirectory(examples/gallery)
add_subdirectory(examples/remote_component_gallery)
if(APPLE)
    set_target_properties(oneui_gallery PROPERTIES MACOSX_BUNDLE TRUE
        MACOSX_BUNDLE_GUI_IDENTIFIER "org.oneui.gallery")
    set_target_properties(oneui_gallery PROPERTIES INSTALL_RPATH "@executable_path/../Frameworks")
else()
    set_target_properties(oneui_gallery PROPERTIES INSTALL_RPATH "$ORIGIN/../lib")
endif()
include("${CMAKE_CURRENT_LIST_DIR}/OneUIInstall.cmake")
if(BUILD_TESTING)
    oneui_register_native_tests()
endif()
