# Export the same reviewed link closure that CMake actually uses. Consumers
# must not recreate a second dependency list (notably the Win7 FreeType path).
if(WIN32 AND MSVC AND ONEUI_BUILD_STATIC AND ONEUI_SKIA_MODE STREQUAL "bundled-static")
    get_target_property(_sdk_archives oneui_skia INTERFACE_LINK_LIBRARIES)
    list(INSERT _sdk_archives 0 "$<TARGET_FILE:oneui_static>" "$<TARGET_FILE:oneui_text>" "$<TARGET_FILE:oneui_skia>")
    list(REMOVE_DUPLICATES _sdk_archives)
    get_target_property(_sdk_system oneui_static INTERFACE_LINK_LIBRARIES)
    get_target_property(_sdk_text_system oneui_text INTERFACE_LINK_LIBRARIES)
    list(APPEND _sdk_system ${_sdk_text_system})
    list(REMOVE_ITEM _sdk_system oneui_text oneui_skia)
    list(REMOVE_DUPLICATES _sdk_system)
    if(CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(_sdk_arch "x86_64")
    else()
        set(_sdk_arch "x86")
    endif()
    if(ONEUI_WINDOWS_BASELINE STREQUAL "win7")
        set(_sdk_profile "legacy")
    else()
        set(_sdk_profile "modern")
    endif()
    file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/sdk-inputs-$<CONFIG>.json" CONTENT
"{\n  \"schemaVersion\": 1,\n  \"profile\": \"${_sdk_profile}\",\n  \"architecture\": \"${_sdk_arch}\",\n  \"configuration\": \"$<CONFIG>\",\n  \"compiler\": \"${CMAKE_CXX_COMPILER}\",\n  \"archives\": [\"$<JOIN:${_sdk_archives},\",\">\"],\n  \"systemLibraries\": [\"$<JOIN:${_sdk_system},\",\">\"]\n}\n")
endif()
