# The production text engine is mandatory, including for headless core tests.
set(_oneui_text_modules skparagraph skshaper skunicode_icu skunicode_core)
if(ONEUI_SKIA_MODE STREQUAL "msys2-dynamic")
    foreach(_header modules/skparagraph/include/Paragraph.h modules/skunicode/include/SkUnicode_icu.h src/core/SkLRUCache.h src/core/SkTHash.h)
        if(NOT EXISTS "${SKIA_ROOT}/include/skia/${_header}")
            message(FATAL_ERROR "Full OneUI text engine requires ${SKIA_ROOT}/include/skia/${_header}. The installed development Skia package is incomplete; do not mix headers from another revision. Build the pinned Skia and its text modules with the matching toolchain.")
        endif()
    endforeach()
    foreach(_module IN LISTS _oneui_text_modules)
        find_library(ONEUI_TEXT_${_module} NAMES ${_module} PATHS "${SKIA_ROOT}/lib" NO_DEFAULT_PATH REQUIRED)
        target_link_libraries(oneui_skia INTERFACE "${ONEUI_TEXT_${_module}}")
    endforeach()
    target_link_libraries(oneui_skia INTERFACE icuuc)
else()
    set(ONEUI_ICU_ROOT "${ONEUI_BUNDLED_SKIA_ROOT}/third_party/externals/icu")
    set(ONEUI_ICU_CHECK_ONLY ON)
    include("${CMAKE_CURRENT_LIST_DIR}/../scripts/apply-skia-patches.cmake")
    unset(ONEUI_ICU_CHECK_ONLY)
    foreach(_module IN LISTS _oneui_text_modules)
        if(NOT EXISTS "${ONEUI_BUNDLED_SKIA_OUT}/${_module}.lib" AND NOT EXISTS "${ONEUI_BUNDLED_SKIA_OUT}/lib${_module}.a")
            message(FATAL_ERROR "Required Skia text module ${_module} missing. Rebuild the pinned Skia with skparagraph and skunicode_icu targets.")
        endif()
    endforeach()
endif()

add_library(oneui_text STATIC src/text/text_layout.cpp src/text/font_manager.cpp src/text/canvas_text.cpp)
set_target_properties(oneui_text PROPERTIES POSITION_INDEPENDENT_CODE ON)
target_include_directories(oneui_text PRIVATE include src)
target_link_libraries(oneui_text PUBLIC oneui_skia)
target_compile_definitions(oneui_text PRIVATE ONEUI_BUILDING_DLL)
if(ONEUI_SKIA_MODE STREQUAL "bundled-static")
    target_include_directories(oneui_text PRIVATE "${ONEUI_BUNDLED_SKIA_ROOT}/third_party/externals/icu/source/common")
    target_compile_definitions(oneui_text PRIVATE U_STATIC_IMPLEMENTATION U_DISABLE_RENAMING=1)
    if(WIN32)
        set(_oneui_icu_data "${ONEUI_BUNDLED_SKIA_ROOT}/third_party/externals/icu/common/icudtl.dat")
        set(_oneui_icu_source "${CMAKE_CURRENT_BINARY_DIR}/generated/icu_data.cpp")
        file(MAKE_DIRECTORY "${CMAKE_CURRENT_BINARY_DIR}/generated")
        add_custom_command(OUTPUT "${_oneui_icu_source}"
            COMMAND ${CMAKE_COMMAND} "-DINPUT=${_oneui_icu_data}" "-DOUTPUT=${_oneui_icu_source}"
                -P "${CMAKE_CURRENT_SOURCE_DIR}/cmake/EmbedIcuData.cmake"
            DEPENDS "${_oneui_icu_data}" "${CMAKE_CURRENT_SOURCE_DIR}/cmake/EmbedIcuData.cmake" VERBATIM)
        target_sources(oneui_text PRIVATE src/text/icu_data_win32.cpp "${_oneui_icu_source}")
        target_compile_definitions(oneui_text PRIVATE ONEUI_EMBEDDED_ICU=1)
    endif()
endif()
if(WIN32)
    target_link_libraries(oneui_text PUBLIC dwrite gdi32 user32 ole32 oleaut32 uuid windowscodecs fontsub usp10 advapi32)
    target_compile_definitions(oneui_text PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
elseif(APPLE)
    target_link_libraries(oneui_text PUBLIC "-framework CoreText" "-framework CoreGraphics" "-framework CoreFoundation")
else()
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(ONEUI_TEXT_FONTCONFIG REQUIRED IMPORTED_TARGET fontconfig)
    target_link_libraries(oneui_text PUBLIC PkgConfig::ONEUI_TEXT_FONTCONFIG)
endif()
