function(oneui_add_core_test target source)
    add_executable(${target} ${source})
    target_link_libraries(${target} PRIVATE oneui_core)
    target_compile_definitions(${target} PRIVATE ONEUI_BUILDING_DLL)
    add_test(NAME ${target} COMMAND ${target})
endfunction()

function(oneui_add_native_test target source)
    add_executable(${target} ${source})
    target_link_libraries(${target} PRIVATE oneui)
    add_test(NAME ${target} COMMAND ${target})
endfunction()

function(oneui_register_core_tests)
    oneui_add_core_test(oneui_control_behavior_tests tests/control_behavior_tests.cpp)
    oneui_add_core_test(oneui_time_series_chart_behavior_tests tests/time_series_chart_behavior_tests.cpp)
    oneui_add_core_test(oneui_selection_model_tests tests/selection_model_tests.cpp)
    oneui_add_core_test(oneui_overlay_host_behavior_tests tests/overlay_host_behavior_tests.cpp)
    oneui_add_core_test(oneui_scroll_view_behavior_tests tests/scroll_view_behavior_tests.cpp)
    oneui_add_core_test(oneui_stack_behavior_tests tests/stack_behavior_tests.cpp)
    oneui_add_core_test(oneui_realtime_frame_view_behavior_tests tests/realtime_frame_view_behavior_tests.cpp)
    oneui_add_core_test(oneui_remote_input_region_behavior_tests tests/remote_input_region_behavior_tests.cpp)
    oneui_add_core_test(oneui_terminal_view_behavior_tests tests/terminal_view_behavior_tests.cpp)
    oneui_add_core_test(oneui_tree_view_behavior_tests tests/tree_view_behavior_tests.cpp)
    oneui_add_core_test(oneui_panel_behavior_tests tests/panel_behavior_tests.cpp)
endfunction()

function(oneui_register_native_tests)
    oneui_add_native_test(oneui_c_api_behavior_tests tests/c_api_behavior_tests.cpp)
    oneui_add_native_test(oneui_time_series_chart_c_api_tests tests/time_series_chart_c_api_tests.cpp)
    oneui_add_native_test(oneui_monitor_behavior_tests tests/monitor_behavior_tests.cpp)
    target_compile_definitions(oneui_monitor_behavior_tests PRIVATE ONEUI_BUILDING_DLL)
    oneui_add_native_test(oneui_backend_contract_tests tests/backend_contract_tests.cpp)
    target_compile_definitions(oneui_backend_contract_tests PRIVATE ONEUI_BUILDING_DLL)

    if(ONEUI_BUILD_STATIC)
        add_executable(oneui_c_api_static_link_tests tests/c_api_behavior_tests.cpp)
        target_link_libraries(oneui_c_api_static_link_tests PRIVATE oneui_static)
        target_compile_definitions(oneui_c_api_static_link_tests PRIVATE ONEUI_STATIC)
        add_test(NAME oneui_c_api_static_link_tests COMMAND oneui_c_api_static_link_tests)
    endif()

    add_test(
        NAME oneui_abi_sync
        COMMAND powershell -NoProfile -ExecutionPolicy Bypass
            -File ${CMAKE_CURRENT_SOURCE_DIR}/scripts/check-abi-sync.ps1)
endfunction()
